accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),    
    path('login', views.login, name='login'),    
    path('logout', views.logout, name='logout'),    
]

coronamap/urls.py
from django.contrib import admin
from django.urls import path, include
from statements import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),    
    path('statements/', include('statements.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

statements/urls.py
from django.urls import path, include
from . import views

#app_name = 'statements'
urlpatterns = [
    path('', views.home, name='home'),  #index
    path('create', views.create, name='create'),    
    path('<int:statement_id>', views.detail, name='detail'),
    path('<int:statement_id>/results', views.results, name='results'),
    path('<int:statement_id>/giveResponseDisagree', views.giveResponseDisagree, name='giveResponseDisagree'),
    path('<int:statement_id>/giveResponseAgree', views.giveResponseAgree, name='giveResponseAgree'),
#    path('<int:statement_id>/upvote', views.upvote, name='upvote'),
#    path('<int:statement_id>/upvote_home', views.upvote_home, name='upvote_home')
]

statements/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count

# see https://docs.djangoproject.com/en/dev/topics/db/models/#extra-fields-on-many-to-many-relationships

# from https://stackoverflow.com/questions/29534257/set-imagefield-default-value-to-random-image-out-of-a-list-of-images-in-django
from pathlib import Path
from random import randint
import time
from django.core.files import File
from django.db import models
allowed_image_extensions = ['.jpg', '.png', '.jpeg']


class Hashtag(models.Model):
#    statement = models.ForeignKey(Statement, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    url = models.TextField()
    icon = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.text

    
class Statement(models.Model):
    statement_text = models.CharField(max_length=200)
#    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    # body = models.TextField()
    # url = models.TextField()
    #blank=True, null=True, 
    image = models.ImageField(default='static/statements/opinion_choice.png', upload_to="images/")
    icon = models.ImageField(default='static/statements/opinion_choice.png',upload_to='images/')
    iconAgree = models.ImageField(default='static/statements/agree.png', upload_to='images/')
    iconDisagree = models.ImageField(default='static/statements/disagree.png', upload_to='images/')
    # votes_total = models.IntegerField(default = 1)    
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    agreeUsers = models.ManyToManyField(User, related_name="agreeUsers")
    disagreeUsers = models.ManyToManyField(User, related_name="disagreeUsers")
    dontcareUsers = models.ManyToManyField(User, related_name="dontcareUsers")
    dontknowUsers = models.ManyToManyField(User, related_name="dontknowUsers")
    hashtags = models.ManyToManyField(Hashtag, related_name="hashtags")

    def __str__(self):
        return self.statement_text[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')  

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Response(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    statement = models.ForeignKey(Statement, on_delete=models.CASCADE)
    response_date = models.DateTimeField()
    agree = models.IntegerField(default = 0)
    disagree = models.IntegerField(default = 0)
    latitude = models.FloatField(default=0, blank=False, null=False)
    longitude = models.FloatField(default=0, blank=False, null=False)

    def __str__(self):
        return self.statement.statement_text

    def __num0__(self):
        return Response.objects.filter(answer=0).count()

class UserGeoLocation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    latitude = models.FloatField(blank=False, null=False)
    longitude = models.FloatField(blank=False, null=False)



################################################################################

def get_file_extension(file_path):
    return Path(file_path).suffix


def get_files_in_directory(directory, absolute_path=False):
    from os import listdir
    from os.path import isfile
    only_files = [f for f in listdir(directory) if isfile("{}/{}".format(directory, f))]

    if not absolute_path:
        return only_files

    else:
        return ["{}/{}".format(directory, file_) for file_ in only_files]


def get_post_image_path(instance, filename):
    path_first_component = 'posts'
    ext = get_file_extension(filename)
    current_time_stamp = int(time.time())
    file_name = '{}/posts_{}_{}{}'.format(path_first_component, instance.id, current_time_stamp, ext)
    full_path = path_first_component + file_name
    return full_path

statements/forms.py
from django.forms import Form, FloatField

class LookupForm(Form):
    latitude = FloatField()
    longitude = FloatField()

statements/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Statement, Response, UserGeoLocation, Hashtag
from django.utils import timezone
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from django.template import loader

from django.views.generic.edit import FormView
from statements.forms import LookupForm
#from django.shortcuts import render_to_response

def home(request):
    # latest_statement_list = Statement.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.statement_text for q in latest_statement_list])
    # return HttpResponse(output)
    # statements = Statement.objects.all().order_by('-pub_date') # gets all the projects out of the database
    # return render(request, 'statements/home.html', {'statements':statements})

    latest_statement_list = Statement.objects.all().order_by('-pub_date')[:5] # gets all the projects out of the database
    template = loader.get_template('statements/home.html') #statements/
    context = {'latest_statement_list':latest_statement_list,}
    return HttpResponse(template.render(context, request))
   # return render(request, 'statements/home.html', {'latest_statement_list':latest_statement_list}) #statements/


#    return render(request, 'statements/home.html', {'statements':statements})
#    output = ', '.join([q.statement_text for q in latest_statement_list])
#    return HttpResponse(output)

@login_required(login_url="/accounts/signup")
def create(request):
    if request.method == 'POST':
        if request.POST['statement_text']:
            statement = Statement()
            statement.statement_text = request.POST['statement_text']
            statement.pub_date = timezone.datetime.now()
            statement.creator = request.user
            if request.FILES['icon_disagree']:
                statement.iconDisagree = request.FILES['icon_disagree']
            if request.FILES['icon_agree']:
                statement.iconAgree = request.FILES['icon_agree']
            if request.FILES['icon']:
                statement.icon = request.FILES['icon']
            statement.save() # inserts it into the database

            return redirect('/statements/' + str(statement.id)) # show user the Statement
        else:
            return render(request, 'statements/create.html', {'error':'All fields are required.'})
    else:
        return render(request, 'statements/create.html')


def detail(request, statement_id):
    statement = get_object_or_404(Statement, pk=statement_id)  #pk=primary key
    return render(request, 'statements/detail.html', {'statement':statement})  #statements/

    # try:
    #     statement = Statement.objects.get(pk=statement_id)
    # except Statement.DoesNotExist:
    #     raise Http404("Statement does not exist")
    # return render(request, 'statements/detail.html', {'statement':statement})

#    return HttpResponse("You're looking at question %s." % statement_id)

# def detail(request, statement_id):
#     statement = get_object_or_404(Statement, pk=statement_id)  #pk=primary key
#     return render(request, 'statements/detail.html', {'statement':statement})  #statements/
    

def results(request, statement_id):
    statement = get_object_or_404(Statement, pk=statement_id)
    numDisagree = Response.objects.filter(statement_id=statement_id).filter(disagree=1).count()
    numAgree = Response.objects.filter(statement_id=statement_id).filter(agree=1).count()
    return render(request, 'statements/results.html', {'statement': statement, 'numDisagree': numDisagree, 'numAgree': numAgree})  #statements/


@login_required(login_url="/accounts/signup")
def giveResponseDisagree(request, statement_id):
    if request.method == 'POST':   
        statement = get_object_or_404(Statement, pk=statement_id)
        response = Response()
        response.user = request.user
        response.statement = statement
        response.response_date = timezone.datetime.now()
        response.disagree = 1
        response.agree = 0
        response.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('results', args=(statement.id,)))    

    # probabyl should put in error handling here...
    # try:
    #     selected_choice = statement.choice_set.get(pk=request.POST['choice'])
    # except (KeyError, Choice.DoesNotExist):
    #     # Redisplay the question voting form.
    #     return render(request, 'statements/detail.html', {
    #         'statement': statement,
    #         'error_message': "You d   idn't select a choice.",
    #     })
    # else:


@login_required(login_url="/accounts/signup")
def giveResponseAgree(request, statement_id):
    if request.method == 'POST':   
        statement = get_object_or_404(Statement, pk=statement_id)
        response = Response()
        response.user = request.user
        response.statement = statement
        response.response_date = timezone.datetime.now()
        response.disagree = 0
        response.agree = 1
        response.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('results', args=(statement.id,)))    


@login_required(login_url="/accounts/signup")
def results0(request, statement_id):
    statement = get_object_or_404(Statement, pk=statement_id)

    #Response.objects.filter(statement_id=2).filter(answer=0).count()

#@login_required(login_url="/accounts/signup")
# def upvote_home(request, statement_id):
#     if request.method == 'POST':        
#         statement = get_object_or_404(statement, pk=statement_id)
#         if request.user not in statement.voters.all():
#             print("not in ")
#             statement.votes_total += 1
#             statement.voters.add(request.user)
#             statement.save() # this save is what actually changes the database
#             return redirect('/statements/' + str(statement.id))
#         else:
#             print("it's already in")
#            # upvote(request, Statement_id)


# @login_required(login_url="/accounts/signup")
# def upvote(request, statement_id):
#     if request.method == 'POST':
#         print("regular upvote")
#         statement = get_object_or_404(statement, pk=statement_id)
#         statement.votes_total += 1
#         statement.voters.add(request.user)
#         statement.save() # this save is what actually changes the database
#         return redirect('/statements/' + str(statement.id))


def save_user_geolocation(request):
    if request.method == 'POST':
        latitude = request.POST['lat']
        longitude = request.POST['long']
        UserGeoLocation.create(
            user = request.user,
            latitude= latitude,
            longitude = longitude,
            )
        return HttpResponse('')


# def index(request):
#     latest_statement_list = Statement.objects.order_by('-pub_date')[:5]
# #    template = loader.get_template('statements/home.html')
#     context = {'latest_statement_list': latest_statement_list}
#     return render(request, 'statements/home.html', context)
#   #  output = ', '.join([q.statement_text for q in latest_statement_list])
#   #  return HttpResponse(output)


# class LookupView(FormView):
#     form_class = LookupForm

#     def get(self, request):
#         return render_to_response('gigs/lookup.html')

#     def form_valid(self, form):
#         # Get data
#         latitude = form.cleaned_data['latitude']
#         longitude = form.cleaned_data['longitude']

#         # Get today's date
#         now = timezone.now()

#         # Get next week's date
#         next_week = now + timezone.timedelta(weeks=1)

#         # Get Point
#         location = Point(longitude, latitude, srid=4326)

#         # Look up events
#         events = Event.objects.filter(datetime__gte=now).filter(datetime__lte=next_week).annotate(distance=Distance('venue__location', location)).order_by('distance')[0:5]

#         # Render the template
#         return render_to_response('gigs/lookupresults.html', {
#             'events': events
#             })

statements/templates/statements/create.html
{% extends 'base.html' %}   

{% block content %}

{% if error %}
    {{ error }}
    <br/>
    <br/>
{% endif %}

<h1>Create</h1>

<form method="POST" action="{% url 'create' %}" enctype="multipart/form-data">
    {% csrf_token %} 
    Statement:<br/>
    <input type="text" name="statement_text" />
    <br/><br/> 
    Hashtag:<br/>
    <input type="text" name="hashtag_text" />
    <br/>
    Icon:<br/>
    <input type="file" name="icon" />
    <br/>
    Disagree Icon:<br/>
    <input type="file" name="icon_disagree" />
    <br/>
    Agree Icon:<br/>
    <input type="file" name="icon_agree" />
    <br/>
    <br/> 
    <input class="btn btn-primary" type="submit" value="Add Statement" />
</form>
{% endblock %}

statements/templates/statements/detail.html
{% extends 'base.html' %}   

{% block content %}

{% load static %}


<h1>{{ statement.statement_text }}</h1>
<img src="{{ statement.image }}" class="img-fluid" />

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- <a href="javascript:{document.getElementById('respond0').submit()}"><button class="btn btn-primary btn-lg btn-block"><ion-icon name="caret-up-outline"></ion-icon> Agree</button></a> -->

<form id="respondDisagree" method="POST" action="{% url 'giveResponseDisagree' statement.id %}">
    {% csrf_token %}
    <input type="hidden">
</form>

<form id="respondAgree" method="POST" action="{% url 'giveResponseAgree' statement.id %}">
    {% csrf_token %}
    <input type="hidden">
</form> 



<link rel="stylesheet" type="text/css" href="{% static 'admin/css/swipe.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {

var animating = false;
var cardsCounter = 0;
var numOfCards = 6;
var decisionVal = 80;
var pullDeltaX = 0;
var deg = 0;
var $card, $cardReject, $cardLike;

function pullChange() {
  animating = true;
  deg = pullDeltaX / 10;
  $card.css("transform", "translateX("+ pullDeltaX +"px) rotate("+ deg +"deg)");

  var opacity = pullDeltaX / 100;
  var rejectOpacity = (opacity >= 0) ? 0 : Math.abs(opacity);
  var likeOpacity = (opacity <= 0) ? 0 : opacity;
  $cardReject.css("opacity", rejectOpacity);
  $cardLike.css("opacity", likeOpacity);
};

function release() {

  if (pullDeltaX >= decisionVal) {
    $card.addClass("to-right");
    document.getElementById("respondAgree").submit();
  } else if (pullDeltaX <= -decisionVal) {
    $card.addClass("to-left");
    document.getElementById("respondDisagree").submit();
  }

  if (Math.abs(pullDeltaX) >= decisionVal) {
    $card.addClass("inactive");

    setTimeout(function() {
      $card.addClass("below").removeClass("inactive to-left to-right");
      cardsCounter++;
      if (cardsCounter === numOfCards) {
        cardsCounter = 0;
        $(".demo__card").removeClass("below");
      }
    }, 300);
  }

  if (Math.abs(pullDeltaX) < decisionVal) {
    $card.addClass("reset");
  }

  setTimeout(function() {
    $card.attr("style", "").removeClass("reset")
      .find(".demo__card__choice").attr("style", "");

    pullDeltaX = 0;
    animating = false;
  }, 300);
  
};

$(document).on("mousedown touchstart", ".demo__card:not(.inactive)", function(e) {
  if (animating) return;

  $card = $(this);
  $cardReject = $(".demo__card__choice.m--reject", $card);
  $cardLike = $(".demo__card__choice.m--like", $card);
  var startX =  e.pageX || e.originalEvent.touches[0].pageX;

  $(document).on("mousemove touchmove", function(e) {
    var x = e.pageX || e.originalEvent.touches[0].pageX;
    pullDeltaX = (x - startX);
    if (!pullDeltaX) return;
    pullChange();
  });

  $(document).on("mouseup touchend", function() {
    $(document).off("mousemove touchmove mouseup touchend");
    if (!pullDeltaX) return; // prevents from rapid click events
    release();
  });


});

});
</script>

<h4>



<div class="demo">
    <header class="demo__header"></header>
    <div class="demo__content">
      <div class="demo__card-cont">
        <div class="demo__card">
          <div class="demo__card__top brown">              
              <style>
                .demo__card__img {
                    overflow: hidden;
                    width: 10rem;
                    height: 10rem;
                    margin: 0 auto 1.5rem;
                    border-radius: 50%;
                    border: 0.5rem solid #fff;
                    background-image: url("{{ statement.image.url }}");
                    background-size: cover;
                }
                </style>
                <img src="{{ statement.image }}" class="img-fluid" />
                <div class="demo__card__img">
                        <img src="{{ statement.image.url }}" class="img-fluid" />

                </div>
            <p class="demo__card__name">{{ statement.statement_text }}</p>
          </div>
          <div class="demo__card__btm">
            <p class="demo__card__we"></p>
          </div>
          <div class="demo__card__choice m--reject"></div>
          <div class="demo__card__choice m--like"></div>
          <div class="demo__card__drag"></div>
        </div>
      </div>
      <p class="demo__tip">Swipe left or right </p>
    </div>
  </div>

  


{% endblock %}


<script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>
<script language="javascript" type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

statements/templates/statements/home.html
{% extends 'base.html' %}   
Statements home

{% block content %}

{% load static %}


Statements home

{% if latest_statement_list %}
    <ul>
    {% for statement in latest_statement_list %}
        <li><a href="{% url 'detail' statement.id %}">{{ statement.statement_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No statements are available.</p>
{% endif %}
</h4>

<!-- 
<form role="form" action="/" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="latitude">Latitude:</label>
        <input id="id_latitude" name="latitude" type="text" class="form-control"></input>
    </div>

    <div class="form-group">
        <label for="longitude">Longitude:</label>
        <input id="id_longitude" name="longitude" type="text" class="form-control"></input>
    </div>

    <input class="btn btn-primary" type="submit" value="Submit" />
</form>

<script language="javascript" type="text/javascript">
    navigator.geolocation.getCurrentPosition(function (position) {
        var lat = document.getElementById('id_latitude');
        var lon = document.getElementById('id_longitude');
        lat.value = position.coords.latitude;
        lon.value = position.coords.longitude;
    });
</script>

{% for product in products.all %}
    <div class="row pb-3">
        <div class="col-2" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer;">    
            <img src="{{ product.icon.url }}" class="img-fluid" height=30 />        
        </div>
        <div class="col-6" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer;">                
            <h1>{{ product.title }}</h1>
            <p>{{ product.summary }}</p>
        </div>
        <div class="col-4" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer;">    
            {% if user in products.all or user == product.hunter %}      
                <a href="#"><button class="btn btn-primary btn-lg btn-block" disabled><ion-icon name="caret-up-outline"></ion-icon> Can't Upvote {{ product.votes_total }}</button></a>            
            {% else %}
                <a href="javascript:{document.getElementById('upvote_home').submit()}"><button class="btn btn-primary btn-lg btn-block"><ion-icon name="caret-up-outline"></ion-icon> Upvote {{ product.votes_total }}</button></a>
            {% endif %}        
        </div>    
    </div>

    <form id="upvote_home{{ product.id }}" method="POST" action="{% url 'upvote_home' product.id %}">
        {% csrf_token %}
        <input type="hidden">
    </form> 

{% endfor %}
-->
{% endblock %}

statements/templates/statements/results.html
{% extends 'base.html' %}   
Statements home

{% block content %}

{% if error %}
    {{ error }}
    <br/>
    <br/>
{% endif %}

<h1>Create</h1>


Results for 
{{ statement.statement_text }}
<br/>Number of disagree responses:
{{ numDisagree }}
<br/>Number of agree responses:
{{ numAgree }}

<a href="{% url 'detail' statement.id %}">Vote again?</a>


{% endblock %}